### ISSUE TITLE
Loading from Teradata to GreenPlum using outsourcer

### ISSUE THREAD

**Issue by ksasi** [pivotalguru/outsourcer#1]
Hi,

Just a thought,is it possible to enhance outsource to load data from Teradata to Greeplum/HAWQ.I am thinking of the use case where customer might want to move from Teradata to Greenplum/HAWQ.

Thanks and Regards,
Sasikanth

**Comment by RunningJon** [comment]
Look at my other project called gplink.  It is similar to Outsourcer but it doesn't have all of the automation.
